### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by 915-Narita-Andrei** [nicohmje/PID-ballonplate#4]
Hello! First of all great job! I was very excited about your project and I also wanted to try it out. Please, could you send me the links of what you bought for this project? Especially for Three DIYMORE Full metal servos, Waveshare Servo HAT, Three Dexter Cardan Joints (Universal joints). I will be very grateful to you! Many thanks and keep up the good work!

**Comment by nicohmje** [comment]
Hello, glad to hear you’re talking on this project! As for product links, if you’re not in France it wouldn’t be a good deal. The servos and cardan joints are the most generic thing ever, you should just look locally for something equivalent! The servo HAT was also something I bought because it was available in a shop near me. Here are the product links if you want the specs: Waveshare Servo Driver Hat Expansion Board Compatible with Raspberry Pi 12-Bit I2C Controlled Straight Pinheader Up to 16-Channel Servo/PWM Outputsamazon.frdiymore 6 pièces Servomoteur numérique à Engrenages en métal Version améliorée Servo de Couple à Grande Vitesse en cuivre Complet pour RC Hélicoptère Avion Voiture Bateau Robot Contrôleuramazon.frhttps://www.leroymerlin.fr/produits/outillage/outillage-a-main/cle/douille/cardan-chrome-vanadium-dexter-diam-15-mm-65996021.htmlLet me know if you need any other information! Cheers,Nicolas H. Sent from my iPhoneOn 22 Oct 2022, at 13:38, Andrei Narita ***@***.***> wrote:﻿
Hello! First of all great job! I was very excited about your project and I also wanted to try it out. Please, could you send me the links of what you bought for this project? Especially for Three DIYMORE Full metal servos, Waveshare Servo HAT, Three Dexter Cardan Joints (Universal joints). I will be very gratefull to you! Many thanks and keep up the good work!
